<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Glady Hazitha Samuel">

<title>Comparative RNA-seq Analysis of SMARCE1 and NF2 Loss in Meningioma</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Deseq2_quarto_files/libs/clipboard/clipboard.min.js"></script>
<script src="Deseq2_quarto_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Deseq2_quarto_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Deseq2_quarto_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Deseq2_quarto_files/libs/quarto-html/popper.min.js"></script>
<script src="Deseq2_quarto_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Deseq2_quarto_files/libs/quarto-html/anchor.min.js"></script>
<link href="Deseq2_quarto_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Deseq2_quarto_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Deseq2_quarto_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Deseq2_quarto_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Deseq2_quarto_files/libs/bootstrap/bootstrap-a74871fe4945b66d259aafc266475145.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#background-on-smarce1" id="toc-background-on-smarce1" class="nav-link" data-scroll-target="#background-on-smarce1">Background on SMARCE1</a></li>
  <li><a href="#data-and-study-design" id="toc-data-and-study-design" class="nav-link" data-scroll-target="#data-and-study-design">Data and Study Design</a></li>
  <li><a href="#rna-seq-workflow" id="toc-rna-seq-workflow" class="nav-link" data-scroll-target="#rna-seq-workflow">RNA-seq Workflow</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  </ul></li>
  <li><a href="#rna-seq-analysis" id="toc-rna-seq-analysis" class="nav-link" data-scroll-target="#rna-seq-analysis">RNA-seq Analysis</a>
  <ul class="collapse">
  <li><a href="#qc-and-alignment" id="toc-qc-and-alignment" class="nav-link" data-scroll-target="#qc-and-alignment">QC and Alignment</a></li>
  <li><a href="#deseq2" id="toc-deseq2" class="nav-link" data-scroll-target="#deseq2">DESEQ2</a></li>
  <li><a href="#import-count-data" id="toc-import-count-data" class="nav-link" data-scroll-target="#import-count-data">Import Count Data</a></li>
  <li><a href="#quality-control-and-filtering" id="toc-quality-control-and-filtering" class="nav-link" data-scroll-target="#quality-control-and-filtering">Quality Control and Filtering</a></li>
  <li><a href="#deseq-dds" id="toc-deseq-dds" class="nav-link" data-scroll-target="#deseq-dds">DESEQ dds</a></li>
  <li><a href="#differentially-expressed-genes" id="toc-differentially-expressed-genes" class="nav-link" data-scroll-target="#differentially-expressed-genes">Differentially Expressed Genes</a></li>
  <li><a href="#deseq2-lfc-shrinkage" id="toc-deseq2-lfc-shrinkage" class="nav-link" data-scroll-target="#deseq2-lfc-shrinkage">DESEQ2 LFC shrinkage</a></li>
  <li><a href="#ma-plots" id="toc-ma-plots" class="nav-link" data-scroll-target="#ma-plots">MA PLOTS</a></li>
  <li><a href="#volcano-plot" id="toc-volcano-plot" class="nav-link" data-scroll-target="#volcano-plot">Volcano Plot</a></li>
  <li><a href="#principal-component-analysis" id="toc-principal-component-analysis" class="nav-link" data-scroll-target="#principal-component-analysis">Principal Component Analysis</a></li>
  <li><a href="#heatmap-visualization" id="toc-heatmap-visualization" class="nav-link" data-scroll-target="#heatmap-visualization">Heatmap Visualization</a></li>
  <li><a href="#top-genes-expression-qc" id="toc-top-genes-expression-qc" class="nav-link" data-scroll-target="#top-genes-expression-qc">Top Genes Expression QC</a></li>
  <li><a href="#go-analysis" id="toc-go-analysis" class="nav-link" data-scroll-target="#go-analysis">GO Analysis</a></li>
  <li><a href="#top-go-terms" id="toc-top-go-terms" class="nav-link" data-scroll-target="#top-go-terms">Top GO Terms</a></li>
  <li><a href="#gsea-analysis" id="toc-gsea-analysis" class="nav-link" data-scroll-target="#gsea-analysis">GSEA Analysis</a></li>
  <li><a href="#upset-plot-go" id="toc-upset-plot-go" class="nav-link" data-scroll-target="#upset-plot-go">Upset Plot GO</a></li>
  <li><a href="#upset-plot-gsea" id="toc-upset-plot-gsea" class="nav-link" data-scroll-target="#upset-plot-gsea">Upset Plot GSEA</a></li>
  <li><a href="#ridge-plots" id="toc-ridge-plots" class="nav-link" data-scroll-target="#ridge-plots">Ridge Plots</a></li>
  <li><a href="#gene-concept-network" id="toc-gene-concept-network" class="nav-link" data-scroll-target="#gene-concept-network">Gene Concept Network</a></li>
  <li><a href="#result-output-files" id="toc-result-output-files" class="nav-link" data-scroll-target="#result-output-files">Result Output Files</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Comparative RNA-seq Analysis of SMARCE1 and NF2 Loss in Meningioma</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Glady Hazitha Samuel </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<section id="background-on-smarce1" class="level2">
<h2 class="anchored" data-anchor-id="background-on-smarce1">Background on SMARCE1</h2>
<p>Clear cell meningiomas are rare and aggressive brain tumors that are characterized by loss of function mutations in SMARCE1 <span class="citation" data-cites="StPierre2022 Smith2013">(<a href="#ref-StPierre2022" role="doc-biblioref">St. Pierre et al. 2022</a>; <a href="#ref-Smith2013" role="doc-biblioref">Smith et al. 2013</a>)</span>. SMARCE1 is a key component of the BAF complex, a chromosome remodelling complex <span class="citation" data-cites="KadochCrabtree2015">(<a href="#ref-KadochCrabtree2015" role="doc-biblioref">Kadoch and Crabtree 2015</a>)</span>. During transcription, the BAF complex regulates gene expression by altering chromosome structure to allow or restrict access to transcription factors, enhancers and other molecules involved in transcription <span class="citation" data-cites="KadochCrabtree2015">(<a href="#ref-KadochCrabtree2015" role="doc-biblioref">Kadoch and Crabtree 2015</a>)</span>. Mutations in components of the BAF complex are often associated with cancers <span class="citation" data-cites="Shain2013">(<a href="#ref-Shain2013" role="doc-biblioref">Shain and Pollack 2013</a>)</span>. Although many of the components of the BAF complex have been well studied, the specific role of SMARCE1 in transcriptional regulation and gene expression is unclear. <img src="smarce1.png" class="img-fluid quarto-figure quarto-figure-center" style="width:70.0%" data-fig-cap="SMARCE1 clear cell meningioma illustration [@Bogershausen2018]."></p>
<p>In this Nature Genetics publication, the authors study the role of SMARCE1 in context of the BAF complex <span class="citation" data-cites="StPierre2022">(<a href="#ref-StPierre2022" role="doc-biblioref">St. Pierre et al. 2022</a>)</span>. Here the authors use various analysis including RNA-seq, ATAC-seq and ChIP-seq to understand this pathway and possible pharmaceutical interventions.</p>
</section>
<section id="data-and-study-design" class="level2">
<h2 class="anchored" data-anchor-id="data-and-study-design">Data and Study Design</h2>
<p>This study uses a combination of RNA-seq, ATAC-seq and ChIP-seq data to study the mechanism by which loss of SMARCE1 results in tumorogenesis. The authors performed comprehensive transcriptomic analysis of SMARCE Null cells compared to WT controls in AC7 arachnoid cells which are used as a meningioma model. They also looked at NF2 deficient AC7 cells which are involved in many fibrous meningiomas.In this project, I specifically focus on the RNASeq analysis and study the key biological pathways involved with loss of SMARCE1 and NF2 to look at pathways that are shared and distinct between the two conditions.The study includes libraries prepared using Illumina Tru-Seq Stranded mRNA Library Prep Kit. Using a AC7 meningioma cell model, clones were established for WT(3 clones-2 replicates each – 6 biological replicates) and SMARCE1 Null(2 Clones- 2 replicates each = 4 biological replicates.). The reads are single end reads of 75bp length sequenced on Illumina NextSeq 500.</p>
</section>
<section id="rna-seq-workflow" class="level2">
<h2 class="anchored" data-anchor-id="rna-seq-workflow">RNA-seq Workflow</h2>
<p>The authors of this paper used STAR and the hg19 human gene annotation file for alignments. The output gene count tables which were then loaded into EdgeR (v.3.12.1) to evaluate differential gene expression. Downstream, the EdgeR log2Fold changes were used for GSEA analysis using the GSEAPreranked Tool (GSEA63). For enrichment of select genes, Metscape or Hypergeomatric tests were used to see which pathways were enriched amongst the select subset of genes. Heatmaps were made based on RPKM values which were convered to z-scores. PCA was performed to show sample level differences using functions from the corpcor package in R.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>The PCA analysis of the samples show a strong separation between the NF2 null and the SMARCE1 null gene expression. In comparison to the WT, the authors found 3456 differentially expressed genes in SMARCE1 Null cells. Of these, 1684 were significantly downregulated and 1772 were upregulated. The paper does not list the numbers for differentially expressed genes in the NF2 null cells. However, in a combined heatmap, the figure shows that 4226 genes were significantly differentially expressed in either SMARCE1 null of NF2 null compared to WT. The full list of differentially expressed genes is not available however, figures show representative genes and categories associated with each condition. These genes are differentially expressed in both Smarce Null and NF2 null compared to WT: FLNA, SOD2, CREB1, SKP2 and STXBP1.</p>
</section>
</section>
<section id="rna-seq-analysis" class="level1">
<h1>RNA-seq Analysis</h1>
<section id="qc-and-alignment" class="level2">
<h2 class="anchored" data-anchor-id="qc-and-alignment">QC and Alignment</h2>
<p>For the intital QC analysis, Fastqc and Multiqc analysis were performed the for single read RNA-seq libraries from the publication. The total number of sequences per sample ranged form 14 million to 60 millions reads. The mean quality phred scores were above 30 for all samples. 4 samples failed the per base sequence content and 1 sample failed the per base GC content. The duplication levels were also high and 36/46 samples failed according to the multiqc. However on further research in the literature, this seems normal for RNAseq data. Overall, the adapter content was low for all samples and all samples passed QC. However, since a few samples showed slight increase in adapters in the 3’ end, I performed adapter trimming. After trimming, the QC report showed the expected improvements. Adapter content was mostly eliminated across all samples, and the per-base quality profile became much more uniform along the read length. Overrepresented sequences also decreased substantially after trimming, as well as the GC content. The main metric that remained unchanged was the duplication levels. Overall, the trimming step effectively addressed the issues I saw in the raw data. This publication did not go into details regarding the initial QC and trimming steps etc. This could be because it included a variety of omics analysis including RNAseq, CHIPseq ,ATACseq and scRNAseq which could be why they did not emphasize the analysis details/methods for RNAseq.</p>
</section>
<section id="deseq2" class="level2">
<h2 class="anchored" data-anchor-id="deseq2">DESEQ2</h2>
</section>
<section id="import-count-data" class="level2">
<h2 class="anchored" data-anchor-id="import-count-data">Import Count Data</h2>
<p>The gene count data from HTSeq were imported and organized into a DESeqDataSet with the experimental design ~ condition to enable differential expression testing between SMARCE1-null, NF2-null, and wild-type samples.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Metadata rows: 14"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Sample files length: 14"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Sample table rows: 14"</code></pre>
</div>
</div>
</section>
<section id="quality-control-and-filtering" class="level2">
<h2 class="anchored" data-anchor-id="quality-control-and-filtering">Quality Control and Filtering</h2>
<p>Wild-type was set as the reference condition for all comparisons. Genes with &lt; than 50 total counts across all samples were filtered out to reduce noise and improve statistical power. The histogram shows the distribution of the log transformed counts.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/factors-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="deseq-dds" class="level2">
<h2 class="anchored" data-anchor-id="deseq-dds">DESEQ dds</h2>
<p>Differential expression testing was performed using DESeq2, which models count data with a negative binomial distribution to account for biological and technical variability. The pipeline estimates normalization factors, dispersion parameters, and performs statistical testing to identify genes with significant expression changes between conditions</p>
</section>
<section id="differentially-expressed-genes" class="level2">
<h2 class="anchored" data-anchor-id="differentially-expressed-genes">Differentially Expressed Genes</h2>
<p>The Differential expression analysis identified 8,037 genes significantly changed in SMARCE1-null cells and 4,067 genes in NF2-null cells (adjusted p-value &lt; 0.1) as seen in the table below. SMARCE1 loss affected nearly twice as many genes as NF2 loss, suggesting a broader transcriptional impact. In the SMARCE1-responsive genes, 3,985 were upregulated and 4,052 were downregulated,showing a balanced transcriptional response with slightly more gene repression. For NF2, 2,103 genes were upregulated and 1,964 downregulated, showing a similar balance between activation and repression. The comparable ratios up and downregulated genes in both conditions suggest that loss of either SMARCE1 or NF2 triggers both activating and repressive transcriptional programs, rather than a unidirectional effect.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
out of 19287 with nonzero total read count
adjusted p-value &lt; 0.1
LFC &gt; 0 (up)       : 3985, 21%
LFC &lt; 0 (down)     : 4052, 21%
outliers [1]       : 1, 0.0052%
low counts [2]     : 1, 0.0052%
(mean count &lt; 1)
[1] see 'cooksCutoff' argument of ?results
[2] see 'independentFiltering' argument of ?results</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
out of 19287 with nonzero total read count
adjusted p-value &lt; 0.1
LFC &gt; 0 (up)       : 2103, 11%
LFC &lt; 0 (down)     : 1964, 10%
outliers [1]       : 1, 0.0052%
low counts [2]     : 1871, 9.7%
(mean count &lt; 5)
[1] see 'cooksCutoff' argument of ?results
[2] see 'independentFiltering' argument of ?results</code></pre>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary of differentially expressed genes (padj &lt; 0.1)</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 38%">
<col style="width: 17%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: center;">Total DE genes (padj &lt; 0.1)</th>
<th style="text-align: center;">Upregulated</th>
<th style="text-align: center;">Downregulated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SMARCE1-null vs WT</td>
<td style="text-align: center;">8037</td>
<td style="text-align: center;">3985</td>
<td style="text-align: center;">4052</td>
</tr>
<tr class="even">
<td style="text-align: left;">NF2-null vs WT</td>
<td style="text-align: center;">4067</td>
<td style="text-align: center;">2103</td>
<td style="text-align: center;">1964</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="deseq2-lfc-shrinkage" class="level2">
<h2 class="anchored" data-anchor-id="deseq2-lfc-shrinkage">DESEQ2 LFC shrinkage</h2>
<p>In order to get more accurate effect size estimates for visualizations, a log2 fold change shrinkage method called ashr was used. This improves individual gene-level estimates by reducing noise for downstream visualizations and analysis such as GSEA.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/shrink-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/shrink-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="ma-plots" class="level2">
<h2 class="anchored" data-anchor-id="ma-plots">MA PLOTS</h2>
<p>MA plots visualize the relationship between mean normalized count and log2 fold change. Significantly differentially expressed genes (padj &lt; 0.1) are highlighted in blue. Based on the plots below we can see that the shrinkage is working correctly.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/maplots-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/maplots-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/maplots-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/maplots-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ensembl gene IDs were annotated with human gene symbols using the org.Hs.eg.db database to facilitate biological interpretation of results.</p>
</section>
<section id="volcano-plot" class="level2">
<h2 class="anchored" data-anchor-id="volcano-plot">Volcano Plot</h2>
<p>Volcano plots visualize the relationship between log2 fold change and -log10 adjusted p-value for all genes. Genes are color-coded by significance where red indicates both statistically significant (padj &lt; 0.1) and biologically meaningful (|log2FC| &gt; 1) changes, while gray represents non-significant genes. The top 15 most significant genes are labeled with gene symbols. SMARCE1 loss affected 8,037 genes while NF2 loss affected 4,067 genes, with both conditions showing similar amounts of up and downregulated genes.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/volcano-plots-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Volcano plots comparing differential gene expression</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/volcano-plots-2.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Volcano plots comparing differential gene expression</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="principal-component-analysis" class="level2">
<h2 class="anchored" data-anchor-id="principal-component-analysis">Principal Component Analysis</h2>
<p>PCA is an important QC figure and it shows the overall relationships of the samples based on gene expression clustering. In our analysis, the first two principal componenets captured about 69% of the variability in gene expression. PC1 separates the WT from the SMARCE1 null while the NF2 null samples are positioned between the WT and SMARCE1 Null, suggesting a gene expression signature that is intermediate between WT and SMARCE1.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/pca-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/pca-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="heatmap-visualization" class="level2">
<h2 class="anchored" data-anchor-id="heatmap-visualization">Heatmap Visualization</h2>
<p>To visualize expression patterns of the most differentially expressed genes, heatmaps were generated of the top 30 genes ranked by absolute log2 fold change. Gene expression was displayed using regularized log-transformed (rlog) counts, which stabilize variance across different expression levels.</p>
<p>Three versions of the heatmap were created: 1. Raw rlog counts : Shows absolute expression levels across all samples 2. baseMean-scaled : Normalizes by average expression to emphasize relative changes 3. WT-scaled : Centers expression relative to wild-type samples to highlight deviations from control</p>
<p>From the plots below, we see that the SMARCE1 clustering is distinct from the WT , while NF2 shows an intermediate clustering which falls between WT and SMARCE1 for the top regulated genes. The plots also shows that the genes are both up and downregulated in the knockdown, suggesting there is an overall transcriptional change which is not directional.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/heatmaps-smarce-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Heatmaps of top 30 differentially expressed genes in SMARCE1-null cells</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/heatmaps-smarce-2.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Heatmaps of top 30 differentially expressed genes in SMARCE1-null cells</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/heatmaps-smarce-3.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Heatmaps of top 30 differentially expressed genes in SMARCE1-null cells</figcaption>
</figure>
</div>
</div>
</div>
<p>Heatmaps were also generated for the NF2 null vs WT comparison to visualize the top 20 genes in each condition.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/heatmaps-nf2-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Heatmaps of top 30 differentially expressed genes in NF2-null cells</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/heatmaps-nf2-2.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Heatmaps of top 30 differentially expressed genes in NF2-null cells</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/heatmaps-nf2-3.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Heatmaps of top 30 differentially expressed genes in NF2-null cells</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="top-genes-expression-qc" class="level2">
<h2 class="anchored" data-anchor-id="top-genes-expression-qc">Top Genes Expression QC</h2>
<p>These individual gene expression plots show the most significantly expressed gene in each condition.<br>
For SMARCE1 null, the top differentially expressed gene shows consistent expression changes across all SMARCE1-null replicates, with tight within-group clustering and clear separation from wild-type controls. This shows that the statistical significance reflects real biological differences. The tight clustering of replicates and clear separation between conditions for these top genes suggests taht the broader differential expression results represent true biological responses to SMARCE1 or NF2 loss, rather than technical noise or batch effects.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/topgenes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/topgenes-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  ensembl_gene_id gene_symbol
1 ENSG00000000003      TSPAN6
2 ENSG00000000419        DPM1
3 ENSG00000000457       SCYL3
4 ENSG00000000460       FIRRM
5 ENSG00000000971         CFH
6 ENSG00000001036       FUCA2
                                                  description
1                                               tetraspanin 6
2 dolichyl-phosphate mannosyltransferase subunit 1, catalytic
3                                    SCY1 like pseudokinase 3
4   FIGNL1 interacting regulator of recombination and mitosis
5                                         complement factor H
6                                        alpha-L-fucosidase 2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19288     3</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Number of significant genes - SMARCE1: 8037 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of significant genes - NF2: 4067 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ENSG00000000003" "ENSG00000000971" "ENSG00000001167" "ENSG00000001461"
[5] "ENSG00000001617" "ENSG00000001629"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ENSG00000000003" "ENSG00000000971" "ENSG00000001461" "ENSG00000001497"
[5] "ENSG00000001629" "ENSG00000002016"</code></pre>
</div>
</div>
</section>
<section id="go-analysis" class="level2">
<h2 class="anchored" data-anchor-id="go-analysis">GO Analysis</h2>
<p>Gene Ontology (GO) enrichment analysis identified the biological processes significantly overrepresented among differentially expressed genes in each knockout condition.</p>
<p>According to the plots below, SMARCE1 loss primarily affects developmental and structural processes wuch as skeletal development, tissue morphogenesis, and extracellular matrix metabolism. The enrichment of negative regulation of cell proliferation suggests disruption of growth control mechanisms whic is consistent with tumor development. These pathways fit with SMARCE1’s role in chromatin remodeling during development.</p>
<p>NF2 loss activates immune and inflammatory signaling pathways—defense responses, cytokine production, and cellular signaling through protein phosphorylation. This is very different from SMARCE1, suggesting that NF2 mutations trigger an immune response and not developmental dysregulation.</p>
<p>These completely different GO profiles suggest that these two genes drive tumorgenesis through different mechanisms. This also fits with the fact that they are associated with different subtypes of meningiomas.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/ego-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/ego-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/ego-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/ego-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="top-go-terms" class="level2">
<h2 class="anchored" data-anchor-id="top-go-terms">Top GO Terms</h2>
<p>According to these plots, ECM genes are significantly downregulated in SMARCE1-null cells</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Top GO term for SMARCE1: GO:0030900 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Description: forebrain development </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/topgo-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Top GO term for NF2: GO:1904752 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Description: regulation of vascular associated smooth muscle cell migration </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/topgo-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="gsea-analysis" class="level2">
<h2 class="anchored" data-anchor-id="gsea-analysis">GSEA Analysis</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/gsea-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/gsea-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="upset-plot-go" class="level2">
<h2 class="anchored" data-anchor-id="upset-plot-go">Upset Plot GO</h2>
<p>Upset plots were generated to visualize the overlap of genes across the top enriched GO terms for each condition. These plots show which genes are shared across multiple biological processes and which are specific to individual pathways.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/unnamed-chunk-1-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="upset-plot-gsea" class="level2">
<h2 class="anchored" data-anchor-id="upset-plot-gsea">Upset Plot GSEA</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/upsetplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/upsetplot-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="ridge-plots" class="level2">
<h2 class="anchored" data-anchor-id="ridge-plots">Ridge Plots</h2>
<p>The SMARCE1 ridgeplot revealed distinct expression patterns across enriched pathways. Developmental and structural pathways showed bimodal or broadly distributed expression, with genes spanning both upregulated and downregulated ranges. In contrast, NF2-null cells showed dramatically different pathway enrichments with strong directional bias. Nearly all enriched pathways displayed distributions shifted far to the right, indicating upregulation:</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/gsea-ridgeplot-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>GSEA ridgeplots showing expression distribution across top enriched pathways</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/gsea-ridgeplot-2.png" class="img-fluid figure-img" width="960"></p>
<figcaption>GSEA ridgeplots showing expression distribution across top enriched pathways</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="gene-concept-network" class="level2">
<h2 class="anchored" data-anchor-id="gene-concept-network">Gene Concept Network</h2>
<p>These network plots help to visualize relationships between enriched GO terms based on shared genes. They show the functional relationships and clustering patterns among biological processes.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deseq2_quarto_files/figure-html/emapplot-clean-1.png" class="img-fluid figure-img" width="1344"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
=== FILES SAVED ===</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>SMARCE1:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - All genes: 19288 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Significant (padj &lt; 0.1): 8037 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Stringent (padj &lt; 0.01 &amp; |FC| &gt; 1): 1902 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>NF2:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - All genes: 19288 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Significant (padj &lt; 0.1): 4067 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Stringent (padj &lt; 0.01 &amp; |FC| &gt; 1): 685 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>All files saved to: /Users/hazitha/Desktop/labs/ISG/RNAseq_sem1/FinalProject_smarce1_meningioma/scripts/05_R_analysis/05_results </code></pre>
</div>
</div>
</section>
<section id="result-output-files" class="level2">
<h2 class="anchored" data-anchor-id="result-output-files">Result Output Files</h2>
<p>05_results/ ├── kadoch_SMARCE1_DESeq2_ALL_genes.csv ├── kadoch_SMARCE1_DESeq2_significant_padj0.1.csv ├── kadoch_SMARCE1_DESeq2_significant_padj0.01_FC1.csv ├── kadoch_NF2_DESeq2_ALL_genes.csv ├── kadoch_NF2_DESeq2_significant_padj0.1.csv ├── kadoch_NF2_DESeq2_significant_padj0.01_FC1.csv ├── kadoch_normalized_counts.txt ├── kadoch_SMARCE1_GO_all.csv ├── kadoch_NF2_GO_all.csv ├── kadoch_SMARCE1_GSEA.csv └── kadoch_NF2_GSEA.csv</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>In this section we will talk about the key findings of the RNA-seq analysis and compare it with the published data.</p>
<p>Key Findings 1. Smarce1 Null cells hows a transcriptional signature that is distinct from WT cells. 2. Loss of Smarce1 results in about half the genes upregulated and half downregulated, suggesting an overall transcriptional activation and repression that is not directional. 3. NF2 null cells also show a similar pattern, however only 3456 genes were differentially expressed compared to Smarce Null cells which had 8037 genes differentially expressed. 4. The PCA plot shows strong and distinct clustering of the Smarce Null and nF2 null suggesting they are transcriptionally different although both are involved in tumorogenesis.</p>
<p>Our analysis identified a larger number of differentially expressed genes (8,037 vs 3,456 for SMARCE1) compared to the original publication where 1,684 genes were significantly downregulated1,772 genes were significantly upregulated. This is likely due to differences in statistical thresholds (padj &lt; 0.05 compared to stricter cut offs), the software versions (DESeq2 vs edgeR v3.12.1) and filtering approaches. However, the ratio of upregulated to downregulated genes remained consistent with the published results, confirming the balanced transcriptional response to SMARCE1 loss.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-KadochCrabtree2015" class="csl-entry" role="listitem">
Kadoch, C., and G. R. Crabtree. 2015. <span>“Mammalian SWI/SNF Chromatin Remodeling Complexes and Cancer: Mechanistic Insights Gained from Human Genomics.”</span> <em>Science Advances</em> 1 (5). <a href="https://doi.org/10.1126/sciadv.1500447">https://doi.org/10.1126/sciadv.1500447</a>.
</div>
<div id="ref-Shain2013" class="csl-entry" role="listitem">
Shain, A. H., and J. R. Pollack. 2013. <span>“The Spectrum of SWI/SNF Mutations, Ubiquitous in Human Cancers.”</span> <em>PLoS ONE</em> 8 (1): e55119. <a href="https://doi.org/10.1371/journal.pone.0055119">https://doi.org/10.1371/journal.pone.0055119</a>.
</div>
<div id="ref-Smith2013" class="csl-entry" role="listitem">
Smith, M. J., J. O’Sullivan, S. S. Bhaskar, K. D. Hadfield, et al. 2013. <span>“Loss-of-Function Mutations in SMARCE1 Cause an Inherited Disorder of Multiple Spinal Meningiomas.”</span> <em>Nature Genetics</em> 45: 295–98. <a href="https://doi.org/10.1038/ng.2552">https://doi.org/10.1038/ng.2552</a>.
</div>
<div id="ref-StPierre2022" class="csl-entry" role="listitem">
St. Pierre, R., C. K. Collings, D. D. Samé Guerra, C. J. Widmer, O. Bolonduro, N. Mashtalir, et al. 2022. <span>“SMARCE1 Deficiency Generates a Targetable mSWI/SNF Dependency in Clear Cell Meningioma.”</span> <em>Nature Genetics</em> 54: 861–73. <a href="https://doi.org/10.1038/s41588-022-01077-0">https://doi.org/10.1038/s41588-022-01077-0</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>